name: Install dependencies

strategy:
  matrix:
    node-version: ['16.x', '18.x', '20.x']

runs:
  using: composite
  steps: # retry in case of server error from registry
    - run: yarn install --ignore-engines || yarn install --ignore-engines
      shell: bash
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

