name: All Green
on:
  pull_request:

jobs:

  all-green:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
    steps:
      - uses: wechuli/allcheckspassed@v1
        with:
          retries: 20 # ~3 times per minute, some checks take up to 5 min
          polling_interval: '0.3'
          checks_exclude: devflow.*
