name: Prepare release proposal

on:
  workflow_dispatch:

jobs:
  create-proposal:
    strategy:
      matrix:
        base-branch:
          - v4.x
          - v5.x
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_ACCESS_TOKEN_RELEASE }}

      - name: Update prerelease-branch
        uses: ./.github/actions/prepare-prerelease
        with:
          base-branch: ${{ matrix.base-branch }}
          github-token: ${{ secrets.GH_ACCESS_TOKEN_RELEASE }}

      - name: Checkout prerelease branch
        run: |
          git checkout ${{ matrix.base-branch }}
          git pull
          git checkout ${{ matrix.base-branch }}-proposal
          git pull

      - name: Get branch diffs
        id: get_branch_diffs
        run: |
          node _scripts/prepare-release-proposal.js print-branch-diffs ${{ matrix.base-branch }} ${{ matrix.base-branch }}-proposal > branch-diffs.txt

      - name: Calculate release type
        id: calc-release-type
        run: |
          release_type=`grep -q "(SEMVER-MINOR)" branch-diffs.txt && echo "minor" || echo "patch"`
          echo "release-type=$release_type" >> $GITHUB_OUTPUT

      - name: Create proposal branch
        id: create_branch
        run: |
          branch_name=`node _scripts/prepare-release-proposal.js create-branch ${{ steps.calc-release-type.outputs.release-type }}`
          echo "branch_name=$branch_name" >> $GITHUB_OUTPUT

      - name: Push proposal branch
        run: |
          git push origin ${{steps.create_branch.outputs.branch_name}}

      - name: Update package.json
        id: pkg
        run: |
          content=`node _scripts/prepare-release-proposal.js update-package-json ${{ steps.calc-release-type.outputs.release-type }}`
          echo "version=$content" >> $GITHUB_OUTPUT

      - name: Create PR
        run: |
          gh pr create --draft --base ${{ matrix.base-branch }} --title "v${{ steps.pkg.outputs.version }}" -F branch-diffs.txt
          rm branch-diffs.txt
        env:
          GH_TOKEN: ${{ github.token }}

      # Commit package.json and push to proposal branch after the PR is created to force CI execution
      - name: Commit package.json
        run: |
          git add package.json
          git commit -m "v${{ steps.pkg.outputs.version }}"

      - name: Push package.json update
        run: |
          git push origin ${{steps.create_branch.outputs.branch_name}}

      - name: Clean _scripts
        run: |
          rm -rf _scripts
